// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Mausr.Web.Controllers
{
    public partial class TeachController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TeachController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StartTeaching()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StartTeaching);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Batch()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Batch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BatchPost()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BatchPost);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ApproveSymbolDrawingsPost()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ApproveSymbolDrawingsPost);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TeachController Actions { get { return MVC.Teach; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Teach";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Teach";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string StartTeaching = "StartTeaching";
            public readonly string Batch = "Batch";
            public readonly string BatchPost = "Batch";
            public readonly string Done = "Done";
            public readonly string ApproveSymbolDrawings = "ApproveSymbolDrawings";
            public readonly string ApproveSymbolDrawingsPost = "ApproveSymbolDrawings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string StartTeaching = "StartTeaching";
            public const string Batch = "Batch";
            public const string BatchPost = "Batch";
            public const string Done = "Done";
            public const string ApproveSymbolDrawings = "ApproveSymbolDrawings";
            public const string ApproveSymbolDrawingsPost = "ApproveSymbolDrawings";
        }


        static readonly ActionParamsClass_StartTeaching s_params_StartTeaching = new ActionParamsClass_StartTeaching();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StartTeaching StartTeachingParams { get { return s_params_StartTeaching; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StartTeaching
        {
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_Batch s_params_Batch = new ActionParamsClass_Batch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Batch BatchParams { get { return s_params_Batch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Batch
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_BatchPost s_params_BatchPost = new ActionParamsClass_BatchPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BatchPost BatchPostParams { get { return s_params_BatchPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BatchPost
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ApproveSymbolDrawings s_params_ApproveSymbolDrawings = new ActionParamsClass_ApproveSymbolDrawings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ApproveSymbolDrawings ApproveSymbolDrawingsParams { get { return s_params_ApproveSymbolDrawings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ApproveSymbolDrawings
        {
            public readonly string savedRows = "savedRows";
            public readonly string skippedRows = "skippedRows";
        }
        static readonly ActionParamsClass_ApproveSymbolDrawingsPost s_params_ApproveSymbolDrawingsPost = new ActionParamsClass_ApproveSymbolDrawingsPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ApproveSymbolDrawingsPost ApproveSymbolDrawingsPostParams { get { return s_params_ApproveSymbolDrawingsPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ApproveSymbolDrawingsPost
        {
            public readonly string approvals = "approvals";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ApproveSymbolDrawings = "ApproveSymbolDrawings";
                public readonly string Batch = "Batch";
                public readonly string Done = "Done";
                public readonly string Index = "Index";
                public readonly string PromoteDrawings = "PromoteDrawings";
            }
            public readonly string ApproveSymbolDrawings = "~/Views/Teach/ApproveSymbolDrawings.cshtml";
            public readonly string Batch = "~/Views/Teach/Batch.cshtml";
            public readonly string Done = "~/Views/Teach/Done.cshtml";
            public readonly string Index = "~/Views/Teach/Index.cshtml";
            public readonly string PromoteDrawings = "~/Views/Teach/PromoteDrawings.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TeachController : Mausr.Web.Controllers.TeachController
    {
        public T4MVC_TeachController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StartTeachingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult StartTeaching(int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StartTeaching);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            StartTeachingOverride(callInfo, count);
            return callInfo;
        }

        [NonAction]
        partial void BatchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Mausr.Web.Models.BatchInitViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Batch(Mausr.Web.Models.BatchInitViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Batch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            BatchOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void BatchPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Mausr.Web.Models.TeachBatchViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult BatchPost(Mausr.Web.Models.TeachBatchViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BatchPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            BatchPostOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DoneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Done()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Done);
            DoneOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ApproveSymbolDrawingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? savedRows, int? skippedRows);

        [NonAction]
        public override System.Web.Mvc.ActionResult ApproveSymbolDrawings(int? savedRows, int? skippedRows)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ApproveSymbolDrawings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "savedRows", savedRows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "skippedRows", skippedRows);
            ApproveSymbolDrawingsOverride(callInfo, savedRows, skippedRows);
            return callInfo;
        }

        [NonAction]
        partial void ApproveSymbolDrawingsPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.IDictionary<string,string> approvals);

        [NonAction]
        public override System.Web.Mvc.ActionResult ApproveSymbolDrawingsPost(System.Collections.Generic.IDictionary<string,string> approvals)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ApproveSymbolDrawingsPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "approvals", approvals);
            ApproveSymbolDrawingsPostOverride(callInfo, approvals);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
